# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 112edf1872725a0df627c745ef8286374eade91750b04ef0b9d0e00a488f73238ef136856c60478a05f369b47f6f5477c5b7d8555eac89fe4462fcfbe8e0b5a6

test:
  secret_key_base: 3cc641dacc963cce8896f2d87b7966edb5738cb3b3ca4e5846c1862b8201ddb8c655f6e585bb0809f269ef9d085abe70563be008152c75613fab2d82025bfdcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
